// 2026年新增红色景点坐标（高德坐标系 GCJ-02）
// image: 单张图片时使用，值为图片路径字符串
// images: 多张图片时使用，值为图片路径数组
const newPoints = [
  {
    lat: 26.084,
    lng: 119.293,
    title: "三坊七巷",
    location: "福建",
    images: [
      "img/new-img/三坊七巷-1.png",
      "img/new-img/三坊七巷-2.png",
      "img/new-img/三坊七巷-3.png",
      "img/new-img/三坊七巷-4.png",
      "img/new-img/三坊七巷-5.png",
      "img/new-img/三坊七巷-6.png",
    ],
    content: "三坊七巷景点介绍（测试文字）。",
  },
  {
    lat: 26.069,
    lng: 119.296,
    title: "上下杭历史文化街区",
    location: "福建",
    images: [
      "img/new-img/上下杭历史文化街区-1.png",
      "img/new-img/上下杭历史文化街区-2.png",
      "img/new-img/上下杭历史文化街区-3.png",
      "img/new-img/上下杭历史文化街区-4.png",
      "img/new-img/上下杭历史文化街区-5.png",
    ],
    content: "上下杭历史文化街区景点介绍（测试文字）。",
  },
  {
    lat: 26.0,
    lng: 119.455,
    title: "中国船政文化景区",
    location: "福建",
    images: [
      "img/new-img/中国船政文化景区-1.png",
      "img/new-img/中国船政文化景区-2.png",
      "img/new-img/中国船政文化景区-3.png",
      "img/new-img/中国船政文化景区-4.png",
      "img/new-img/中国船政文化景区-5.png",
      "img/new-img/中国船政文化景区-6.png",
    ],
    content: "中国船政文化景区景点介绍（测试文字）。",
  },
  {
    lat: 25.223,
    lng: 116.828,
    title: "古田会议会址",
    location: "福建",
    image: "img/new-img/古田会议会址.png",
    content: "古田会议会址景点介绍（测试文字）。",
  },
  {
    lat: 25.222,
    lng: 116.83,
    title: "古田会议纪念馆",
    location: "福建",
    image: "img/new-img/古田会议纪念馆.png",
    content: "古田会议纪念馆景点介绍（测试文字）。",
  },
  {
    lat: 25.06,
    lng: 117.03,
    title: "新罗东肖红色旧址群（东肖革命烈士纪念碑）",
    location: "福建",
    image: "img/new-img/新罗东肖红色旧址群（东肖革命烈士纪念碑）.png",
    content: "新罗东肖红色旧址群景点介绍（测试文字）。",
  },
  {
    lat: 25.224,
    lng: 116.825,
    title: "毛主席纪念园",
    location: "福建",
    image: "img/new-img/毛主席纪念园.png",
    content: "毛主席纪念园景点介绍（测试文字）。",
  },
  {
    lat: 26.048,
    lng: 119.305,
    title: "烟台山",
    location: "福建",
    images: [
      "img/new-img/烟台山-1.png",
      "img/new-img/烟台山-2.png",
      "img/new-img/烟台山-3.png",
      "img/new-img/烟台山-4.png",
      "img/new-img/烟台山-5.png",
    ],
    content: "烟台山景点介绍（测试文字）。",
  },
  {
    lat: 26.08,
    lng: 119.263,
    title: "福山郊野公园",
    location: "福建",
    images: [
      "img/new-img/福山郊野公园-1.png",
      "img/new-img/福山郊野公园-2.png",
      "img/new-img/福山郊野公园-3.png",
      "img/new-img/福山郊野公园-4.png",
      "img/new-img/福山郊野公园-5.png",
    ],
    content: "福山郊野公园景点介绍（测试文字）。",
  },
  {
    lat: 26.078,
    lng: 119.308,
    title: "福建省革命历史纪念馆",
    location: "福建",
    images: [
      "img/new-img/福建省革命历史纪念馆-1.png",
      "img/new-img/福建省革命历史纪念馆-2.png",
      "img/new-img/福建省革命历史纪念馆-3.png",
      "img/new-img/福建省革命历史纪念馆-4.png",
      "img/new-img/福建省革命历史纪念馆-5.png",
    ],
    content: "福建省革命历史纪念馆景点介绍（测试文字）。",
  },
  {
    lat: 25.076,
    lng: 117.01,
    title: "邓子恢故居",
    location: "福建",
    images: ["img/new-img/邓子恢故居-1.png", "img/new-img/邓子恢故居-2.png"],
    content: "邓子恢故居景点介绍（测试文字）。",
  },
].sort((a, b) => a.title.localeCompare(b.title));

export { newPoints };
